version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5001"
      - "7860:7860"
    volumes:
      # Optional: Mount logs for easier debugging
      - ./logs:/var/log/supervisor
    restart: unless-stopped
    # Optional: Add environment variables if needed
    # environment:
    #   - ENV_VAR=value
    
    # Optional: Add health check
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    
    # Optional: Set container name
    container_name: my-app